config/routes.rb
Rails.application.routes.draw do

  root :to => 'static_pages#home'

  resources :age_groups
  resources :locations
  resources :statuses
  resources :boxes
  resources :toys
  resources :users
  resources :sessions

  resources :toys do
    collection { post :import }
  end

  resources :age_groups do
    collection { post :import }
  end

  resources :locations do
    collection { post :import }
  end

  get 'boxes/small_label/:id' => 'boxes#small_label', :as => :small
  get 'boxes/medium_label/:id' => 'boxes#medium_label', :as => :medium
  get 'boxes/large_label/:id' => 'boxes#large_label', :as => :large
  get 'login' => 'sessions#new', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout

end

app/models/toy.rb
class Toy < ActiveRecord::Base
	validates :name, presence:true
	validates :manufacturer_suggested_age, presence:true
	validates :pieces, presence:true

	belongs_to :box
	belongs_to :age_group

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Toy.create! row.to_hash
		end
	end
end

app/controllers/toys_controller.rb
# class CreateToys < ActiveRecord::Migration
#   def change
#     create_table :toys do |t|
#       t.string :name, null:false
#       t.integer :box_id
#       t.string :brand
#       t.integer :age_group_id
#       t.string :upc
#       t.string :manufacturer_suggested_age, null:false
#       t.integer :pieces, null:false
#       t.string :website
#       t.string :purchased_from
#       t.string :price
#       t.string :toy_image

#       t.timestamps null: false
#     end
#   end
# end


class ToysController < ApplicationController
  def index
    @toys = Toy.all
  end

  def create
    @toy = Toy.new(toy_params)
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])

    if@toy.save
      redirect_to :toys, notice: "Success created"
    else
      flash.now[:alert] = "Couldn't create"
      render :new
    end
  end

  def new
    @toy = Toy.new
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @boxes = Box.all
    @box = Box.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
  end

  def edit
    @toy = Toy.find_by_id(params[:id])
  end

  def show
    @toy = Toy.find_by_id(params[:id])
    @age_groups = AgeGroup.all
    @age_group = @toy.age_group
    @boxes = Box.all
    @box = Box.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
  end

  def update
    @toy = Toy.find_by_id(params[:id])
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @boxes = Box.all
    @box = Box.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
    if@toy.update_attributes(toy_params)
      redirect_to toy_path(@toy), notice: "Successfully updated"
    else
      flash.now[:alert] = "Couldn't Update"
      render :new
    end
  end

  def destroy
    @toy = Toy.find_by_id(params[:id])
    @toy.destroy
    redirect_to :toys, notice: "Successfully destroyed!"
  end

  def import
    Toy.import(params[:file])
    redirect_to toys_path
  end


  private
  def toy_params
    params.require(:toy).permit(:name, :box_id, :brand, :age_group_id, :upc, :manufacturer_suggested_age, :pieces, :website, :purchased_from, :price, :toy_image)
  end
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/toys/_form.html.erb
<%= form_for @toy do |t| %>


<% if t.object.errors.any?%>
  <div class="col xs12 s12">
    <% t.object.errors.full_messages.each do |x|%>
      <li>Error: <%= x %></li>
    <% end %>
  </div>
  <% end %>

  <div class="input-field col s12 m10 offset-m1">
    <div><%= t.label :name %></div>
    <div><%= t.text_field :name %></div>
  </div>

<!-- NOT EDITABLE IN TOYS, MUST CHANGE THROUGH BOXES -->

  <div class="input-field col s12 m10 offset-m1">
    <div><%= t.label :brand %></div>
    <div><%= t.text_field :brand %></div>
  </div>

  <!-- DROPDOWN PICK AN AGE GROUP -->
  <div class="input-field col s12 m10 offset-m1">
    <div><%= t.label :age_group_id %></div>
    <select class="icons" id="age_group" name="toy[age_group_id]">
      <option value="" disabled selected>Select Assigned Age Group</option>
      <% @age_groups.each do |a| %>
        <option value="<%= a.id %>"><%= a.age %></option>
      <% end %>
    </select>
  </div>

  <div class="input-field col s12 m10 offset-m1">
    <div><%= t.label :upc %></div>
    <div><%= t.text_field :upc %></div>
  </div>

  <div class="input-field col s12 m10 offset-m1">
    <div><%= t.label :manufacturer_suggested_age %></div>
    <div><%= t.text_field :manufacturer_suggested_age %></div>
  </div>

  <div class="input-field col s12 m10 offset-m1">
    <div><%= t.label :pieces %></div>
    <div><%= t.text_field :pieces %></div>
  </div>

  <div class="input-field col s12 m10 offset-m1">
    <div><%= t.label :website %></div>
    <div><%= t.text_field :website %></div>
  </div>

  <div class="input-field col s12 m10 offset-m1">
    <div><%= t.label :purchased_from %></div>
    <div><%= t.text_field :purchased_from %></div>
  </div>

  <div class="input-field col s12 m10 offset-m1">
    <div><%= t.label :price %></div>
    <div><%= t.text_field :price %></div>
  </div>

  <div class="input-field col s12 m10 offset-m1">
    <div><%= t.label :toy_image %></div>
    <div><%= t.text_field :toy_image %></div>
  </div>


  <div class="col sm10 offset-m1">
    <span class="waves-effect right waves-light newPackBtn btn amber lighten-1">
      <%= t.submit %>
    </span>
  </div>
<% end %>

app/views/toys/create.html.erb
<h1>Toys#create</h1>
<p>Find me in app/views/toys/create.html.erb</p>

app/views/toys/destroy.html.erb
<h1>Toys#destroy</h1>
<p>Find me in app/views/toys/destroy.html.erb</p>

app/views/toys/edit.html.erb
<div class="row">
	<h3>Edit Toy</h3>
	<%= render "form" %>
</div>

app/views/toys/index.html.erb
<div class="container">
<ul class="collection with-header">
        <li class="collection-item">
          <div> <span class="fontSize17">All Toys</span>
            <%= link_to new_toy_path(@toy) do %>
              <i class="material-icons amber-text text-darken-1 secondary-content">
                library_add
              </i>
            <% end %>
          </div>
        </li>
    <% @toys.each do |t|%>
    <li class="collection-item avatar">
      <img src="<%= t.toy_image %>" alt="" class="circle">
      <span class="title"><%= link_to t.name, toy_path(t)%></span>
      <p class="secondary-content">
				<%= t.age_group.age %>
      </p>
    </li>
	<% end %>
</ul>

<h3>Import Toys</h3>
<%= form_tag import_toys_path, multipart: true do %>
  <%= file_field_tag :file%>
  <%= submit_tag "Upload Toys" %>
<% end %>
</div>

app/views/toys/new.html.erb
<div class="container">
	<div class="row">
		<%= render "form" %>
	</div>
</div>

app/views/toys/show.html.erb
<div class="container">
      <div class="row">
        <div class="col s12 m8 offset-m2">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title white-text"><%= @toy.name %></span><br>
              <span class="white-text left">Age Group: <%= @toy.age_group.age %></span><br><br>
              		<div class="toy-image-show center-align">
              			<img class="responsive-img " src="<%= @toy.toy_image %>">
              		</div>
            </div>
            <div class="card-action white-text">
              <span class="fontSize17 amber-text text-darken-1">Box: <%= link_to @box.name, box_path(@box)  %></span>
              <span class="amber-text text-darken-1 secondary-content">
              	<%= @status.category %>
              </span>
            </div>
          </div>
        </div>
      </div>
</div>

app/views/toys/update.html.erb
<h1>Toys#update</h1>
<p>Find me in app/views/toys/update.html.erb</p>