config/routes.rb
Rails.application.routes.draw do

  root :to => 'static_pages#home'

  resources :age_groups
  resources :locations
  resources :statuses
  resources :boxes
  resources :toys
  resources :users
  resources :sessions

  resources :toys do
    collection { post :import }
  end

  resources :age_groups do
    collection { post :import }
  end

  resources :locations do
    collection { post :import }
  end

  get 'boxes/small_label/:id' => 'boxes#small_label', :as => :small
  get 'boxes/medium_label/:id' => 'boxes#medium_label', :as => :medium
  get 'boxes/large_label/:id' => 'boxes#large_label', :as => :large
  get 'login' => 'sessions#new', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  	validates :first_name, presence: true
  	validates :last_name, presence: true
  	validates :role, presence:true

		validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
		validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
		validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

		validates :email, uniqueness: true
				  
	has_many :boxes
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create]
  
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @boxes = Box.all
    @box = Box.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "Saved"
    else
      render :new
    end
  end

  private 
	def user_params
		params.require(:user).permit(:first_name, :last_name, :role, :email, :password, :password_confirmation)
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if f.object.errors.any?%>
    <div class="col xs12 s12">
      <% f.object.errors.full_messages.each do |x|%>
        <p>Error: <%= x %></p>
        <p>User was not saved </p>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div>
    <%= f.label :role %><br />
    <%= f.text_field :role %>
  </div>

  <div>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>

  <div>
     <%= f.label :password %><br />
     <%= f.password_field :password %>
  </div>

  <div>
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<div class="container">
	<ul class="collection with-header">
        <li class="collection-item">
        	<div> <span class="fontSize17">All Users</span>
						<%= link_to new_user_path(@user) do %>
	        		<i class="material-icons amber-text text-darken-1 secondary-content">
	        			library_add
	        		</i>
						<% end %>
        	</div>
        </li>
	    <% @users.each do |u|%>
		  <li class="collection-item">
		    <div><%= link_to u.first_name, user_path(u)%> <%= link_to u.last_name, user_path(u)%>
		    <span class="secondary-content">
					<%= u.role %>
				</span>
		    </div>
			</li>
		<% end %>
	</ul>
</div>

app/views/users/new.html.erb
<div class="container">
	<div class="row">
		<%= render "form" %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m8 offset-m2">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title white-text"><%= @user.first_name %> <%= @user.last_name %></span><br>
          <div class="user-image-show center-align">
						<ul class="collection">
							<% if @box.user_id %>
							<% @boxes.where(status:1).find_each do |b|%>
							<li class="collection-item ">
								<span class="title"><%= b.name %></span><br>
							</li>
							<% end %>
							<% end %>
						</ul>
          </div>
          <div class="card-action white-text">
            <span class="fontSize17 white-text text-darken-1">Email: <%= @user.email %></span>
            <span class="fontSize17 white-text text-darken-1 right">
                Phone: <%= @user.phone %>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>