config/routes.rb
Rails.application.routes.draw do

  root :to => 'static_pages#home'

  resources :age_groups
  resources :locations
  resources :statuses
  resources :boxes
  resources :toys
  resources :users
  resources :sessions

  resources :toys do
    collection { post :import }
  end

  resources :age_groups do
    collection { post :import }
  end

  resources :locations do
    collection { post :import }
  end

  get 'boxes/small_label/:id' => 'boxes#small_label', :as => :small
  get 'boxes/medium_label/:id' => 'boxes#medium_label', :as => :medium
  get 'boxes/large_label/:id' => 'boxes#large_label', :as => :large
  get 'login' => 'sessions#new', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout

end

app/models/box.rb
class Box < ActiveRecord::Base
	validates :name, presence:true
	validates :status_id, presence:true
	validates :location_id, presence:true


	def pieces
		piecesArray = []
		
		piecesArray.push(x)
	end

	has_many :toys
	belongs_to :age_group
	belongs_to :status
	belongs_to :location
	belongs_to :user
end

app/controllers/boxes_controller.rb
# class CreateBoxes < ActiveRecord::Migration
#   def change
#     create_table :boxes do |t|
#       t.string :name, null: false
#       t.integer :age_group_id
#       t.integer :status_id, null: false
#       t.integer :user_id
#       t.integer :location_id, null: false

#       t.timestamps null: false
#     end
#   end
# end


class BoxesController < ApplicationController
  def index
    @boxes = Box.all
  end

  def create
    @box = Box.new(box_params)
    @boxes = Box.all
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
    @locations = Location.all
    @location = Location.find_by_id(params[:id])
    @toys = Toy.all
    @toy = Toy.find_by_id(params[:id])
    @users = User.all
    @user = User.find_by_id(params[:id])

    if@box.save
      redirect_to :boxes, notice: "Success created"
    else
      flash.now[:alert] = "Couldn't create"
      render :new
    end
  end

  def new
    @box = Box.new
    @boxes = Box.all
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
    @locations = Location.all
    @location = Location.find_by_id(params[:id])
    @toys = Toy.all
    @toy = Toy.find_by_id(params[:id])
    @users = User.all
    @user = User.find_by_id(params[:id])

  end

  def edit
    @box = Box.find_by_id(params[:id])
    @boxes = Box.all
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
    @locations = Location.all
    @location = Location.find_by_id(params[:id])
    @toys = Toy.all
    @toy = Toy.find_by_id(params[:id])
    @users = User.all
    @user = User.find_by_id(params[:id])
  end

  def labels
    @box = Box.find_by_id(params[:id])
    @boxes = Box.all
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
    @locations = Location.all
    @location = Location.find_by_id(params[:id])
    @toys = Toy.all
    @toy = Toy.find_by_id(params[:id])
    @users = User.all
    @user = User.find_by_id(params[:id])
  end


  def show
    @box = Box.find_by_id(params[:id])
    @boxes = Box.all
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
    @locations = Location.all
    @location = Location.find_by_id(params[:id])
    @toys = Toy.all
    @toy = Toy.find_by_id(params[:id])
    @users = User.all
    @user = User.find_by_id(params[:id])
  end

  def small_label
    @box = Box.find_by_id(params[:id])
    @boxes = Box.all
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
    @locations = Location.all
    @location = Location.find_by_id(params[:id])
    @toys = Toy.all
    @toy = Toy.find_by_id(params[:id])
    @users = User.all
    @user = User.find_by_id(params[:id])
  end

  def medium_label
    @box = Box.find_by_id(params[:id])
    @boxes = Box.all
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
    @locations = Location.all
    @location = Location.find_by_id(params[:id])
    @toys = Toy.all
    @toy = Toy.find_by_id(params[:id])
    @users = User.all
    @user = User.find_by_id(params[:id])
  end

  def large_label
    @box = Box.find_by_id(params[:id])
    @boxes = Box.all
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
    @locations = Location.all
    @location = Location.find_by_id(params[:id])
    @toys = Toy.all
    @toy = Toy.find_by_id(params[:id])
    @users = User.all
    @user = User.find_by_id(params[:id])
  end

  def update
    @box = Box.find_by_id(params[:id])
    @boxes = Box.all
    @age_groups = AgeGroup.all
    @age_group = AgeGroup.find_by_id(params[:id])
    @statuses = Status.all
    @status = Status.find_by_id(params[:id])
    @locations = Location.all
    @location = Location.find_by_id(params[:id])
    @toys = Toy.all
    @toy = Toy.find_by_id(params[:id])
    @users = User.all
    @user = User.find_by_id(params[:id])

    if@box.update_attributes(box_params)
      redirect_to box_path(@box), notice: "Successfully updated"
    else
      flash.now[:alert] = "Couldn't Update"
      render :new
    end
  end

  def destroy
    @box = Box.find_by_id(params[:id])
    @box.destroy
    redirect_to :boxes, notice: "Successfully destroyed!"
  end

  private
  def box_params
    params.require(:box).permit(:name, :age_group_id, :status_id, :user_id, :location_id)
  end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.erb
<%= form_for @box do |b| %>


<% if b.object.errors.any?%>
  <div class="col xs12 s12">
    <% b.object.errors.full_messages.each do |x|%>
      <li>Error: <%= x %></li>
    <% end %>
  </div>
  <% end %>

  <div class="input-field col s12 m10 offset-m1">
    <div><%= b.label :name %></div>
    <div><%= b.text_field :name %></div>
  </div>


  <!-- DROPDOWN PICK AN AGE GROUP -->
  <div class="input-field col s12 m10 offset-m1">
    <div><%= b.label :age_group_id %></div>
    <select class="icons" id="age_group" name="box[age_group_id]">
      <option value="" disabled selected>Select Assigned Age Group</option>
      <% @age_groups.each do |a| %>
        <option value="<%= a.id %>"><%= a.age %></option>
      <% end %>
    </select>
  </div>

  <!-- DROPDOWN PICK A STATUS -->
  <div class="input-field col s12 m10 offset-m1">
    <div><%= b.label :status_id %></div>
    <select class="icons" id="status" name="box[status_id]">
      <option value="" disabled selected>Select Status</option>
      <% @statuses.each do |s| %>
        <option value="<%= s.id %>"><%= s.category %></option>
      <% end %>
    </select>
  </div>

  <!-- DROPDOWN PICK A USER -->
  <div class="input-field col s12 m10 offset-m1">
    <div><%= b.label :user_id %></div>
    <select class="icons" id="user" name="box[user_id]">
      <option value="" disabled selected>Select User</option>
      <% @users.each do |s| %>
        <option value="<%= s.id %>"><%= s.first_name %><%= s.last_name %></option>
      <% end %>
    </select>
  </div>

  <!-- DROPDOWN PICK A LOCATION -->
  <div class="input-field col s12 m10 offset-m1">
    <div><%= b.label :location_id %></div>
    <select class="icons" id="location" name="box[location_id]">
      <option value="" disabled selected>Select Location</option>
      <% @locations.each do |l| %>
        <option value="<%= l.id %>"><%= l.branch_name %></option>
      <% end %>
    </select>
  </div>

  <!-- CHECKLIST FOR SELECTING MULTIPLE TOYS TO BELONG TO THIS BOX-->
      <ul>
      <% @toys.each  do |t| %>
        <li>
          <%= check_box_tag(t) %>
          <%= label_tag(t, t.name) %>
        </li>
      <% end %>
      </ul>




  <div class="col sm10 offset-m1">
    <span class="waves-effect right waves-light newPackBtn btn amber lighten-1">
      <%= b.submit %>
    </span>
  </div>
<% end %>

app/views/boxes/_large_label.html.erb
            
      <div class="row">
        <div class="col s12 m8 offset-m2">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
            	<div class="left">
          			<%= image_tag("tll-logo.png", class:"responsive-img") %>
	            </div>
	            <div class="right">
	              <span class="card-title white-text"><%= @box.name %></span><br>
	              <span class="white-text fontSize17">Total Number of Pieces</span>
	            </div>
							<ul class="collection">
								  <% if @toy.box_id %>
							  		<% @toys.where(box_id:@box.id).find_each do |t|%>
								    <li class="collection-item avatar">
								      <img src="<%= t.toy_image %>" alt="" class="circle">
								      <span class="title"><%= t.name %></span><br>
											<span class="fontSize12"><%= t.pieces %> pieces</span>
								    </li>
								    <% end %>
								  <% end %>
								</ul>
            </div>
            <div class="card-action">
              <%= link_to edit_box_path(@box) do %>
								<i class="fa fa-pencil-square-o fa-2x left white-text" aria-hidden="true"></i>
							<% end %>
							<span class="left"><%= @status.category %></span>
							<%= link_to box_path(@box), method: :delete do %>
								<i class="fa fa-trash fa-2x right white-text" aria-hidden="true"></i>
							<% end %>
            </div>
          </div>
        </div>
      </div>

app/views/boxes/create.html.erb
<h1>Boxes#create</h1>
<p>Find me in app/views/boxes/create.html.erb</p>

app/views/boxes/destroy.html.erb
<h1>Boxes#destroy</h1>
<p>Find me in app/views/boxes/destroy.html.erb</p>

app/views/boxes/edit.html.erb
<div class="container">
	<div class="row">
		<h3>Edit Box</h3>
		<%= render "form" %>
	</div>
</div>

app/views/boxes/index.html.erb
<div class="container">
  

     <ul class="collection with-header">
        <li class="collection-item">
        	<div> <span class="fontSize17">All Boxes</span>
						<%= link_to new_toy_path(@toy) do %>
	        		<i class="material-icons amber-text text-darken-1 secondary-content">
	        			library_add
	        		</i>
						<% end %>
        	</div>
        </li>

    		<% @boxes.each do |b|%>
	        <li class="collection-item">
	        	<div><%= link_to b.name, box_path(b)%>
	        		<span class="secondary-content">
								<%= b.age_group.age %>
							</span>
	        	</div>
	        </li>
	      <% end %>
      </ul>
      </div>

app/views/boxes/large_label.html.erb
<div class="container margintop60px">

	<div class ="<%= @age_group.color %> largeLabel">
		<div class="row">
			<span class="col s12  center-align boxText">
				<h1 class= "col s4"><%= @box.name %></h1>
				<h5 class=" col s8 lineHeight12 center-align"><%= @age_group.age %><br>
				<span class="fontxs">15 pieces</span></h5>
			</span>
			<div class="col s12 inlineBlock largeToySection">
				<% if @toy.box_id %>
					<% @toys.where(box_id:@box.id).find_each do |t|%>
						<div class="inlineBlock height130px white col s6 largeToyRow center">
							<img src="<%= t.toy_image %>" alt="" class="responsive-img">
							<p class="font12 margin0"><%= t.name %><br>
								<span class="font10"> <%= t.pieces %> Pieces </span>
							</p>
						</div>
						<% end %>
					<% end %>`
				</div>
		</div>
	</div>
</div>

app/views/boxes/medium_label.html.erb
<div class="container margintop60px">

	<div class ="<%= @age_group.color %> medLabel">
		<div class="row">
			<span class="col s3  center-align boxText">
				<h4><%= @box.name %></h4>
				<p class="lineHeight12 center-align"><%= @age_group.age %><br>
				<span class="fontxs">15 pieces</span></p>
			</span>
			<div class="col s9 inlineBlock medToySection">
				<% if @toy.box_id %>
					<% @toys.where(box_id:@box.id).find_each do |t|%>
						<div class="inlineBlock height102px white col s6 medToyRow center">
							<img src="<%= t.toy_image %>" alt="" class="responsive-img">
							<p class="fontxs margin0"><%= t.name %> (<%= t.pieces %>)
							</p>
						</div>
						<% end %>
					<% end %>`
				</div>
		</div>
	</div>
</div>

app/views/boxes/new.html.erb
<div class="container">
	<div class="row">
		<%= render "form" %>
	</div>
</div>

app/views/boxes/show.html.erb
<div class="container">      
      <div class="row">
        <div class="col s12 m8 offset-m2">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title white-text"><%= @box.name %>- </span>
              <span class="white-text fontSize17">Total Number of Pieces</span>
							<ul class="collection">
								  <% if @toy.box_id %>
							  		<% @toys.where(box_id:@box.id).find_each do |t|%>
								    <li class="collection-item avatar">
								      <img src="<%= t.toy_image %>" alt="" class="circle">
								      <span class="title"><%= t.name %></span><br>
											<span class="fontSize12"><%= t.pieces %> pieces</span>
								    </li>
								    <% end %>
								  <% end %>
								</ul>
            </div>
            <div class="card-action">
              <%= link_to edit_box_path(@box) do %>
								<i class="fa fa-pencil-square-o fa-2x left white-text" aria-hidden="true"></i>
							<% end %>
							<span class="left"><%= @status.category %></span>
							<%= link_to box_path(@box), method: :delete do %>
								<i class="fa fa-trash fa-2x right white-text" aria-hidden="true"></i>
							<% end %>
            </div>
          </div>
        </div>
      </div>

</div>

app/views/boxes/small_label.html.erb
<div class="container margintop60px">
	<div class ="<%= @age_group.color %> smLabel">
		<div class="row">
			<span class="col s2 center">
				<h4><%= @box.name %></h4>
				<p class="lineHeight12"><%= @age_group.age %><br>
				<span class="fontxs">15 pieces</span></p>
			</span>
			<div class="col s10 inlineBlock">
				<% if @toy.box_id %>
					<% @toys.where(box_id:@box.id).find_each do |t|%>
						<div class="inlineBlock height116px white col s3 smToyRow center">
							<img src="<%= t.toy_image %>" alt="" class="responsive-img">
							<p class="fontxs margin0"><%= t.name %> (<%= t.pieces %>)
							</p>
						</div>
						<% end %>
					<% end %>
				</div>
		</div>
	</div>
</div>

app/views/boxes/update.html.erb
<h1>Boxes#update</h1>
<p>Find me in app/views/boxes/update.html.erb</p>