config/routes.rb
Rails.application.routes.draw do

  root :to => 'static_pages#home'

  resources :age_groups
  resources :locations
  resources :statuses
  resources :boxes
  resources :toys
  resources :users
  resources :sessions

  resources :toys do
    collection { post :import }
  end

  resources :age_groups do
    collection { post :import }
  end

  resources :locations do
    collection { post :import }
  end

  get 'boxes/small_label/:id' => 'boxes#small_label', :as => :small
  get 'boxes/medium_label/:id' => 'boxes#medium_label', :as => :medium
  get 'boxes/large_label/:id' => 'boxes#large_label', :as => :large
  get 'login' => 'sessions#new', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>The Toy Lending Library</title>
<link rel="icon" 
      type="image/png" 
      href="http://www.toylendinglibrary.com/wp-content/uploads/2015/09/cropped-TLLFav-32x32.png">
 <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  <script src="https://use.fontawesome.com/9492ea8d89.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

          
  </head>
  <body>


<nav class="light-green" role="navigation">
  <div class="nav-wrapper container">
          <%= image_tag("tll-logo.png", class:"brand-logo") %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down positionTop30">
      <li class="fontSize12 navWidth center-align">
        <%= link_to "Toys", toys_path %>
      </li>
      <li class="fontSize12 navWidth center-align">
        <%= link_to "Boxes", boxes_path %>
      </li>
      <li class="fontSize12 navWidth center-align">
        <%= link_to "Locations", locations_path %>
      </li>
      <li class="fontSize12 navWidth center-align">
        <%= link_to "Users", users_path %>
      </li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li class="fontSize12 navWidth left-align">
        <%= link_to "Toys", toys_path %>
      </li>
      <li class="fontSize12 navWidth left-align">
        <%= link_to "Boxes", boxes_path %>
      </li>
      <li class="fontSize12 navWidth left-align">
        <%= link_to "Locations", locations_path %>
      </li>
      <li class="fontSize12 navWidth left-align">
        <%= link_to "Users", users_path %>
      </li>
    </ul>
  </div>
</nav>


  <div class="section no-pad-bot" id="index-banner">
      
      <%= yield %>

      <br><br>

  </div>


  <footer class="page-footer  light-green lighten-1">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="">Company Bio</h5>
          <p class="">The Toy Lending Library seeks to place age-appropriate toys in the hands of children. Free to everyone, our process is simple: visit one of our four Toy Lending Library locations and, using an ID and contact information, check out the box of choice and return it to the library within 3 weeks.</p>
        </div>
        <div class="col l3 s12">
          <h5 class="">Locations</h5>
          <ul>
            <li><a class="black-text" href="/locations/1">Main Branch</a></li>
            <li><a class="black-text" href="/locations/2">Downtown Public Library</a></li>
            <li><a class="black-text" href="/locations/3">Oak View Public Library</a></li>
            <li><a class="black-text" href="/locations/4">Ronning Public Library</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="">Main Branch Hours</h5>
          <ul class="">
            <li class="">M 10:00am to 1:00pm</li>
            <li class="">W 11:00am to 1:00pm</li>
            <li class="">Th 4:00pm to 6:00pm</li>
            <li class="">F 9:30am to 11:15am</li>
            <li class="light-italic">Also open by appointment: (605) 215-0575</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container black-text">
      Made by <a class="black-text" href="http://gdavida.github.io/dgPortfolio">Davida Gaffney</a>
      </div>
    </div>
    <!-- jQuery first, then MAterialize JS. -->
      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>

<script type="text/javascript">
  $(document).ready(function() {
  $(".dropdown-button").dropdown();
    $(".button-collapse").sideNav();
  $('select').material_select();
  $('label').addClass('active');
});
</script>
       

  </body>
</html>